---
title: Título

author:
  - name: Carlos Lezama
    affiliation: a,1,2
  - name: Marco Medina
    affiliation: a,1,2
  - name: Emiliano Ramírez
    affiliation: a,1,2
  - name: Santiago Villarreal
    affiliation: a,1,2
address:
  code: a
  address: Instituto Tecnológico Autónomo de México

equal_authors:
  code: 1
  text: "Todos los autores contribuyeron a este trabajo por igual."

corresponding_author:
  code: 2
  text: "Trabajo presentado para el curso de **Simulación (EST-24107)** impartido por Jorge Francisco de la Vega Góngora. E-mail: jorge.delavegagongora@gmail.com"

lead_author_surname: Lezama, Medina, Ramírez y Villarreal

abstract: |
  Please provide an abstract of no more than 250 words in a single paragraph. Abstracts should explain to the general reader the major contributions of the article. References in the abstract must be cited in full within the abstract itself and cited in the text.

keywords:
  - análisis bayesiano
  - aproximación estocástica
  - estimación
  - muestreo de importancia

pnas_type: pnasresearcharticle

bibliography: ref.bib
csl: pnas.csl

lineno: false

output:
  rticles::pnas_article:
    highlight: pygments
---

```{r setup, include=FALSE}
library(rmarkdown)
library(tidyverse)

options(digits = 4)
knitr::opts_chunk$set(
  cache = FALSE,
  dpi = 50,
  echo = TRUE,
  fig.align = "left",
  fig.width = 3.5,
  fig.height = 2
)

theme_set(theme_minimal())
theme_update(panel.grid.minor = element_blank(),
             panel.grid.major = element_blank(),
             text = element_text(size = 6),
             axis.text = element_text(size = 6),
             axis.title = element_text(size = 6),
             plot.title = element_text(size = 6),
             legend.text = element_text(size = 6),
             legend.title = element_text(size = 6))
```

# Introducción {-}

Ejemplo de cita @mainArt.

\lipsum[2-4]

# Datos {-}

```{r data, echo = FALSE}
df <- na.omit(read.csv("data/cancer.csv"))
data <- df$DFS..in.months.
```

\lipsum[4-6]

# Métodos {-}

\lipsum[6-8]

# Resultados {-}

```{r gamma.moments}
gamma.moments <- function(
        data, iters, alpha.0, beta.0
) {
  sample.mean <- mean(data)
  sample.var <- var(data)
  mu.0 <- c(sample.mean, sample.var)
  theta <- matrix(NA, 2, iters)
  theta[, 1] <- c(alpha.0, beta.0)

  for (i in 2:iters) {
    n <- i + 100
    simulated <- rgamma(
            n,
            shape = theta[1, i - 1],
            scale = theta[2, i - 1]
    )
    mu <- c(mean(simulated), var(simulated))
    mu.hat <- matrix(0, 2, 2)
    h <- u <- NULL

    for (j in 1:length(simulated)) {
      u[1] <- -digamma(theta[1, i - 1]) -
              log(theta[2, i - 1]) +
              log(simulated[j])
      u[2] <- (-theta[1, i - 1] / theta[2, i - 1]) +
              simulated[j] / (theta[2, i - 1]^2)
      h[1] <- simulated[j]
      h[2] <- (simulated[j] - mean(simulated))^2
      m <- h %*% t(u)
      mu.hat <- mu.hat + m
    }

    mu.hat <- mu.hat / length(simulated)

    par <- theta[, i - 1] +
            solve(mu.hat) %*% (mu.0 - mu)

    if (par[1] * par[2] > 0) {
      theta[, i] <- par
    } else {
      theta[, i] <- theta[, i - 1] +
              runif(1)
    }
  }

  theta <- data.frame(
          x = theta[1,],
          y = theta[2,],
          n = 1:iters
  )

  p.1 <- ggplot(theta) +
          geom_line(aes(x = n, y = x),
                    size = 0.1) +
          labs(title = NULL,
               x = "n",
               y = expression(alpha))

  p.2 <- ggplot(theta) +
          geom_line(aes(x = n, y = y),
                    size = 0.1) +
          labs(title = NULL,
               x = "n",
               y = expression(beta))

  shape <- mean(theta$x)
  scale <- mean(theta$y)

  dist.mean <- mean(shape * scale)
  dist.var <- mean(shape * (scale^2))

  test <- ks.test(
          data, "pgamma",
          shape = shape, scale = scale
  )

  results <- list(
          test,
          p.1, p.2,
          shape, scale,
          dist.mean, dist.var,
          sample.mean, sample.var
  )

  return(results)
}
```

```{r tests, echo = FALSE, warning = FALSE}
set.seed(1234)
test.1 <- gamma.moments(data, 1000, 0.01, 0.01)
test.1[[1]]; test.1[[2]]; test.1[[3]]; test.1[[4]]; test.1[[5]]; test.1[[6]]; test.1[[7]]; test.1[[8]]; test.1[[9]]
set.seed(1234)
test.2 <- gamma.moments(data, 1000, 2.5, 16.5)
test.2[[1]]; test.2[[2]]; test.2[[3]]; test.2[[4]]; test.2[[5]]; test.2[[6]]; test.2[[7]]; test.2[[8]]; test.2[[9]]
set.seed(1234)
test.3 <- gamma.moments(data, 1000, 20, 50)
test.3[[1]]; test.3[[2]]; test.3[[3]]; test.3[[4]]; test.3[[5]]; test.3[[6]]; test.3[[7]]; test.3[[8]]; test.3[[9]]
```

\lipsum[8-10]

# Conclusiones {-}

\lipsum[10-12]

# Anexos {-}

<!-- No cambiar nada desde aquí -->
# Referencias {-}

\showmatmethods
\showacknow
\pnasbreak
